// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc9997.Pearland_9997v2.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc9997.Pearland_9997v2.OI;
import org.usfirst.frc9997.Pearland_9997v2.Robot;
import org.usfirst.frc9997.Pearland_9997v2.subsystems.*;

/**
 *
 */
public class  ArmPutdown extends Command {
    public static BallGrabber ballGrabber = new BallGrabber();

    public ArmPutdown() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.ballGrabber);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        System.out.println("SpinRightArm Init");
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        System.out.println("SpinRightArm Executed");
        ballGrabber.rightArm.set(-.5);
        ballGrabber.leftArm.set(-.5);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {

        while(OI.btnLeftBumper.get())
        {}
        return true;
     //   System.out.println("button is" + OI.btnBlueX.get());
     //    return OI.btnBlueX.get();
    }

    // Called once after isFinished returns true
    protected void end() {
        ballGrabber.rightArm.set(0);
        ballGrabber.leftArm.set(0);
        System.out.println("SpinRightArm Stop");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
